const allocation = [
    "Seed Round",
    "Private Round",
    "Private Round 2",
    "Liqudity",
    "Marketing",
    "Future develop",
    "Team",
    "Advisor",
    "Advisor",
    "Staking",
];
const share = [
    "3%",
    "9%",
    "3%",
    "1,7%",
    "15%",
    "35%",
    "10%",
    "3%",
    "0,3%",
    "20%",
];
const totalToken = [
    "30 000 000",
    "90 000 000",
    "30 000 000",
    "17 000 000",
    "150 000 000",
    "350 000 000",
    "100 000 000",
    "30 000 000",
    "3 000 000",
    "200 000 000",
];
const price = [
    "0,0004$",
    "0,0006$",
    "0,001$",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
];
const raised = [
    "12000$",
    "54000$",
    "30000$",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
];
const fullLock = [
    "18 month",
    "18 month",
    "12 month",
    "",
    "6 month",
    "6 month",
    "24 month",
    "12 month",
    "",
    "6 month",
];
const vesting = [
    "18 month",
    "18 month",
    "12 month",
    "",
    "6 month",
    "6 month",
    "24 month",
    "12 month",
    "",
    "6 month",
]

export const data = [
    {
        "Allocation": allocation[0],
        "Share": share[0],
        "total token": totalToken[0],
        "price": price[0],
        "raised": raised[0],
        "full lock": fullLock[0],
        "Vesting": vesting[0],
    },
    {
        "Allocation": allocation[1],
        "Share": share[1],
        "total token": totalToken[1],
        "price": price[1],
        "raised": raised[1],
        "full lock": fullLock[1],
        "Vesting": vesting[1],
    },
    {
        "Allocation": allocation[2],
        "Share": share[2],
        "total token": totalToken[2],
        "price": price[2],
        "raised": raised[2],
        "full lock": fullLock[2],
        "Vesting": vesting[2],
    },
    {
        "Allocation": allocation[3],
        "Share": share[3],
        "total token": totalToken[3],
        "price": price[3],
        "raised": raised[3],
        "full lock": fullLock[3],
        "Vesting": vesting[3],
    },
    {
        "Allocation": allocation[4],
        "Share": share[4],
        "total token": totalToken[4],
        "price": price[4],
        "raised": raised[4],
        "full lock": fullLock[4],
        "Vesting": vesting[4],
    },
    {
        "Allocation": allocation[5],
        "Share": share[5],
        "total token": totalToken[5],
        "price": price[5],
        "raised": raised[5],
        "full lock": fullLock[5],
        "Vesting": vesting[5],
    },
    {
        "Allocation": allocation[6],
        "Share": share[6],
        "total token": totalToken[6],
        "price": price[6],
        "raised": raised[6],
        "full lock": fullLock[6],
        "Vesting": vesting[6],
    },
    {
        "Allocation": allocation[7],
        "Share": share[7],
        "total token": totalToken[7],
        "price": price[7],
        "raised": raised[7],
        "full lock": fullLock[7],
        "Vesting": vesting[7],
    },
    {
        "Allocation": allocation[8],
        "Share": share[8],
        "total token": totalToken[8],
        "price": price[8],
        "raised": raised[8],
        "full lock": fullLock[8],
        "Vesting": vesting[8],
    },
    {
        "Allocation": allocation[9],
        "Share": share[9],
        "total token": totalToken[9],
        "price": price[9],
        "raised": raised[9],
        "full lock": fullLock[9],
        "Vesting": vesting[9],
    },
];
export const footer = [
    "Total:",
    "100%",
    "1 000 000 000",
    "",
    "96 000$",
    "",
    "",
]
